name: Archivage TOTO

on: [push]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: ðŸ§¾ Checkout repository
        uses: actions/checkout@v4

      - name: ðŸ—“ï¸ CrÃ©er ou mettre Ã  jour rapport datÃ©
        run: |
          echo TOTO.txt > Q1_archive_TOTO.txt

      - name: ðŸ”„ Commit et push des fichiers gÃ©nÃ©rÃ©s
        run: |
          git config --global user.name "bilelIUT"
          git config --global user.email "bilelenplus@gmail.com"
          git add TOTO.txt Q1_archive_TOTO.txt
          git commit -m "Archivage TOTO.txt" || echo "Aucun changement Ã  valider"
          git push
